"""
generator — PoE FanController KiCad project generator package.

Public API:
    build_schematic()  → Schematic   (from generator.components)
    write_bom()                       (from generator.bom)

P-KI-07: PCB generation is intentionally NOT exported.
         The .kicad_pcb file must not be regenerated by this package.
"""

from .components import build_schematic
from .bom import write_bom

__all__ = ["build_schematic", "write_bom"]
